version: '3.8'
services:
  db:
    image: postgres
    container_name: t3_blog
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DATABASE=t3_blog
    ports:
      - '2345:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local