import Head from "next/head";
import PostFeedItem from "~/components/post/feedItem";
import { api } from "~/utils/api";

export default function Home() {

  const list = api.post.getPageList.useQuery();

  console.log(list, 'list')

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostFeedItem />
      </main>
    </>
  );
}